# This defines the configuration of this application. Each defines a (sub) component that is loaded and
# used for this application. These components can provide specific functionality and define how different
# files in your app are loaded.
rest: true  # This provides the HTTP REST interface for all exported resources
graphqlSchema:  # These reads GraphQL schemas to define the schema of database/tables/attributes.
  files: '*.graphql' # looks for these files
  # path: / # exported queries are on the root path by default
jsResource: # Loads JavaScript modules such that their exports are exported as resources
  files: resources.js # the entry module for resources
'@harperdb/apollo':
  package: '@harperdb/apollo'
  files: '*.{graphql,js}'
  resolvers: 'resolvers.js'
  schemas: '*.graphql'
